- name: installing pkg's
  apt:
      update_cache=yes
      cache_valid_time=172800
      pkg={{item}} state=installed 
  with_items:
    - htop
    - nload
    - vim
    - screen
    - tzdata
    - language-pack-ru


- name: update tzdata
  apt:
      pkg=tzdata state=latest 

- name: set sysctl params
  sysctl: name={{item.name}} value={{item.value}} state=present reload=yes
  with_items:
    - {name: vm.swappiness, value: 0}
    - {name: net.ipv6.conf.all.disable_ipv6, value: 1}
    - {name: net.ipv6.conf.default.disable_ipv6, value: 1}
    - {name: net.ipv6.conf.lo.disable_ipv6, value: 1}

- name: set timezone
  template: src=timezone.j4 dest=/etc/timezone owner=root mode=0644
  notify: set timezone
